on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'        # Release branches
      - 'hotfix/**'         # Hotfix branches
      - master              # Main project branch
  pull_request:

# Quality Assurance
name: code

jobs:
  check:
    name: Check compliance
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
      # Setup Java environment
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Check if code is spotless
      - name: Check code format compliance
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: spotlessJavaCheck -s
