on:
  workflow_dispatch:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'

# Continuous integration
name: build

jobs:
  build:
    name: Build and test on Linux
    runs-on: ubuntu-latest
    env:
      PZ_VERSION: "41.50"
    steps:
      # Checkout repository
      - uses: actions/checkout@v2
      # Setup Java environment
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Cache gradle temporary files
      - name: Cache gradle files
        uses: actions/cache@v2
        with:
          path: ./.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      # Install Project Zomboid classes
      - name: Install Zomboid classes
        uses: dsaltares/fetch-gh-release-asset@0.06
        with:
          repo: "pzstorm/zomboid"
          version: "tags/v41.50"
          file: "zomboid-41.50.jar"
          target: "lib/zomboid-41.50.jar"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # Apply correct permissions for lib directory
      - name: Apply directory permissions
        run: sudo chmod a+rwx ./lib
      # Assemble main classes with gradle
      - name: Assemble classes
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: classes -s
      # Run unit tests with gradle
      - name: Run Unit Tests
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: test -s
      # Upload test reports as run artifact
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-report-${{ runner.os }}
          path: ./build/reports/tests/
